### ISSUE TITLE
humanize duplicate app

### ISSUE THREAD

**Issue by banesullivan** [girder/django-composed-configuration#133]
I'm seeing an error from 59ce6338a046f31d89c8e5543f55fc379c726e8c / #132

```
django.core.exceptions.ImproperlyConfigured: Application labels aren't unique, duplicates: humanize
```

<details>

```
test run-test: commands[0] | pytest --cov=rgd --cov=geodata
Traceback (most recent call last):
  File "/opt/django-project/.tox/test/bin/pytest", line 8, in <module>
    sys.exit(console_main())
  File "/opt/django-project/.tox/test/lib/python3.8/site-packages/_pytest/config/__init__.py", line 185, in console_main
    code = main()
  File "/opt/django-project/.tox/test/lib/python3.8/site-packages/_pytest/config/__init__.py", line 143, in main
    config = _prepareconfig(args, plugins)
  File "/opt/django-project/.tox/test/lib/python3.8/site-packages/_pytest/config/__init__.py", line 318, in _prepareconfig
    config = pluginmanager.hook.pytest_cmdline_parse(
  File "/opt/django-project/.tox/test/lib/python3.8/site-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/opt/django-project/.tox/test/lib/python3.8/site-packages/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/opt/django-project/.tox/test/lib/python3.8/site-packages/pluggy/manager.py", line 84, in <lambda>
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File "/opt/django-project/.tox/test/lib/python3.8/site-packages/pluggy/callers.py", line 203, in _multicall
    gen.send(outcome)
  File "/opt/django-project/.tox/test/lib/python3.8/site-packages/_pytest/helpconfig.py", line 100, in pytest_cmdline_parse
    config: Config = outcome.get_result()
  File "/opt/django-project/.tox/test/lib/python3.8/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/opt/django-project/.tox/test/lib/python3.8/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/opt/django-project/.tox/test/lib/python3.8/site-packages/_pytest/config/__init__.py", line 1003, in pytest_cmdline_parse
    self.parse(args)
  File "/opt/django-project/.tox/test/lib/python3.8/site-packages/_pytest/config/__init__.py", line 1283, in parse
    self._preparse(args, addopts=addopts)
  File "/opt/django-project/.tox/test/lib/python3.8/site-packages/_pytest/config/__init__.py", line 1191, in _preparse
    self.hook.pytest_load_initial_conftests(
  File "/opt/django-project/.tox/test/lib/python3.8/site-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/opt/django-project/.tox/test/lib/python3.8/site-packages/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/opt/django-project/.tox/test/lib/python3.8/site-packages/pluggy/manager.py", line 84, in <lambda>
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File "/opt/django-project/.tox/test/lib/python3.8/site-packages/pluggy/callers.py", line 208, in _multicall
    return outcome.get_result()
  File "/opt/django-project/.tox/test/lib/python3.8/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/opt/django-project/.tox/test/lib/python3.8/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/opt/django-project/.tox/test/lib/python3.8/site-packages/pytest_django/plugin.py", line 322, in pytest_load_initial_conftests
    _setup_django()
  File "/opt/django-project/.tox/test/lib/python3.8/site-packages/pytest_django/plugin.py", line 224, in _setup_django
    django.setup()
  File "/opt/django-project/.tox/test/lib/python3.8/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/opt/django-project/.tox/test/lib/python3.8/site-packages/django/apps/registry.py", line 93, in populate
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: Application labels aren't unique, duplicates: humanize
```

</details>

**Comment by banesullivan** [comment]
Ahhh nevermind. I thought I check RGD to see if humanize was listed but missed it.

This is resolved by https://github.com/ResonantGeoData/ResonantGeoData/pull/345/files#diff-2c77f7552f3fa334decbc44137040144e567d15cbb3c076a6dd71f0ffbe8ba79L68
